### ISSUE TITLE
Arduino cannot execute

### ISSUE THREAD

**Issue by CHNleing** [Mixiaoxiao/Arduino-HomeKit-ESP8266#1]
excuse me. I encountered a problem while testing the example. Aruino IDE tells me:
homekit/types.h: No such file or directory
homekit/homekit.h: No such file or directory
homekit/characteristics.h: No such file or directory

I installed through the management library

**Comment by CHNleing** [comment]
额。。。没细看 北京人啊，
请教下 我在arduino IDE中打开示例文件进行编译时出现错误。
无法找到homekit相关的文件。
还请帮忙看下，

**Comment by CHNleing** [comment]
Found the problem.
I should put arduino_homekit_server.h on top 

#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <arduino_homekit_server.h>
#include <homekit/types.h>
#include <homekit/homekit.h>
#include <homekit/characteristics.h>

**Comment by euler271** [comment]
Libraries <homekit/types.h>, <homekit/homekit.h> and <homekit/characteristics.h> are not required for the example to work. The should be omitted from simple_led.ino. I recently created a pull request to fix this issue.

**Comment by Mixiaoxiao** [comment]
Thanks. I used a little bit intelligent IDE Sloeber(based on eclipse) to build this library and did not meet this issue.
