### ISSUE TITLE
WiFi Connection status

### ISSUE THREAD

**Issue by Eng-Abdulsalam** [Mixiaoxiao/Arduino-HomeKit-ESP8266#101]
Hi Mixiaoxiao, 

Thank you for this Homekit project it is working as expected.

This project was not working for me at the beginning. I was facing an issue but I was not sure why , after troubleshooting I found that the WiFi SSID was not typed correctly (SSID is case sensitive).

It is better to have some serial output to identify WiFi connection status.

### example code to be added:

 
  _// while wifi not connected yet, print 'not connected'
  // then after it connected, get out of the loop
  while (WiFi.status() != WL_CONNECTED) {
     delay(500);
     Serial.println("not connected");
  }
  //print a new line, then print WiFi connected and the IP address
  Serial.println("");
  Serial.println("WiFi connected");
  // Print the IP address
  Serial.println(WiFi.localIP());_

Again thanks a lot.

**Comment by Mixiaoxiao** [comment]
Not an issue. Only one thing unknown for beginners.
