### ISSUE TITLE
Loss of every clients

### ISSUE THREAD

**Issue by Supermarco333** [Mixiaoxiao/Arduino-HomeKit-ESP8266#102]
Hello,

I use my ESP8266 as a CO2 sensor. Everything is perfectly working expect when it doesn't. It appears that my HomeKit accessory sometimes refuses to connect to clients. Rebooting or resetting doesn't help, it keeps logging "HomeKit clients: 0" I have to regenerate keys and restart the pairing process. This problem already occurred 2 times.

Any idea ? Thanks.

**Comment by tatleung** [comment]
@Supermarco333,

Were you able to resolve the issue you reported.  I think I am encountering the similar problem.  In my case, I notice when I restart my ESP8266, the client would not reconnect if my Home app is running on my phone.  However, if I restart the Home app, it will reconnect correctly.

Thanks!
