### ISSUE TITLE
only one client is allowed to pair 

### ISSUE THREAD

**Issue by Eng-Abdulsalam** [Mixiaoxiao/Arduino-HomeKit-ESP8266#104]
Hi

I am using the "switch" example and found that I am able to discover and pair with the esp from apple Home application on the first client only but other clients are not able to find and connect.  

Regards

**Comment by Eng-Abdulsalam** [comment]
Is this a code limitation or it is from apple homekit ?

**Comment by sircuri** [comment]
I don’t think that is even possible on any Homekit device. You have to pair on one device and share your “home” with other people so they can operate the devices as well.
