### ISSUE TITLE
Temperature sensor and switch

### ISSUE THREAD

**Issue by error105** [Mixiaoxiao/Arduino-HomeKit-ESP8266#106]
There is any option that i can add temperature sensor and switch in one ESP8266 devices ?

**Comment by Varogkorn** [comment]
Yes, Sure you can have a look at my file.
[DHT22withLED.zip](https://github.com/Mixiaoxiao/Arduino-HomeKit-ESP8266/files/5982570/DHT22withLED.zip)
I add DHT22 report Temperature and Humidity and I also Have a switch Control 2 LED with Physical(Push Button) In the same ESP8266.

**Comment by yepkevin612** [comment]
@Varogkorn Thank you, so much
