### ISSUE TITLE
ESP8266 cannot boot when PIN is connected

### ISSUE THREAD

**Issue by adriankae** [Mixiaoxiao/Arduino-HomeKit-ESP8266#107]
Hi @Mixiaoxiao,

everything works great so far and I've achieved to realize a dimmable LED Panel. 
It runs on 100V DC so I'm controlling a MOSFET on PIN D4.

Everything works. Until I unplug the ESP8266 from power (5V USB) and plug it in again.

The Serial Monitor gives me this and doesn't stop: 
``n⸮e⸮⸮%⸮!⸮maA⸮%!ai⸮icCneaA⸮o⸮e⸮⸮k⸮!⸮eaA⸮k!!a⸮maAo%!A⸮m⸮e⸮⸮k⸮C⸮eaA⸮Epd⸮s⸮⸮⸮c⸮b⸮⸮r⸮l ⸮⸮ol⸮;⸮⸮o'obl#l`{d⸮d#$⸮{#dcd⸮s{lcd⸮r⸮⸮⸮b⸮#⸮⸮;⸮$`⸮⸮nl⸮{⸮⸮ogn#$cl {d⸮dcd⸮sclcd⸮r{lcl⸮;⸮⸮⸮#⸮c⸮⸮⸮{⸮d`⸮⸮g$⸮{⸮⸮'ogcdc$`sl⸮lcl⸮rclcl⸮;s$#l⸮{⸮Ãc⸮c⸮⸮`

When I disconnect PIN D4 it boots normally.
Any idea what might be the problem?

**Comment by awasspl** [comment]
Read the Pinout Reference for esp8266

https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/
