### ISSUE TITLE
Stateless programable switch 

### ISSUE THREAD

**Issue by yepkevin612** [Mixiaoxiao/Arduino-HomeKit-ESP8266#108]
what happen is this
![WeChat Image_20210110150733](https://user-images.githubusercontent.com/76036097/104116695-f6085980-5355-11eb-94a6-b3e9ec32588a.jpg)

**Comment by awasspl** [comment]
It's becouse You have to be able to create automation assing to it.
If You don't have home hub (appleTV, homepod or ipad) buttonis unusful becouse it's not trigering any action by him self.

**Comment by alexandrerochasalles** [comment]
About this "issue", is there anyway to contour this and use it without a home hub?? 
Maybe using an ESP as a "hub" or "bridge" or something like that??
