### ISSUE TITLE
soft WDT reset

### ISSUE THREAD

**Issue by Izac9** [Mixiaoxiao/Arduino-HomeKit-ESP8266#110]
Hi, i'm getting this watchdog problem when trying to move my stepper more than 1%
`0x40222858: HardwareSerial::write(unsigned char const*, unsigned int) at C:\Users\semte\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266/HardwareSerial.h line 164
0x40100499: __digitalWrite(uint8_t, uint8_t) at C:\Users\semte\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\core_esp8266_wiring_digital.cpp line 86
0x40100470: delayMicroseconds(unsigned int) at C:\Users\semte\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\core_esp8266_wiring.cpp line 210
0x4021d716: Stepper_28BYJ_48::setOutput(int) at C:\Users\semte\Documents\Arduino\libraries\Stepper_28BYJ_48\src\Stepper_28BYJ_48.cpp line 43
0x40216e8e: UpdatePosition() at C:\Users\semte\Documents\Arduino\libraries\HomeKit-ESP8266\examples\window_covering/window_covering.ino line 170
0x40216f44: cha_target_position_setter(homekit_value_t) at C:\Users\semte\Documents\Arduino\libraries\HomeKit-ESP8266\examples\window_covering/window_covering.ino line 122
0x40100913: umm_free_core(void*) at C:\Users\semte\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\umm_malloc\umm_malloc.cpp line 351
0x40216294: homekit_characteristic_ex_old_setter at C:\Users\semte\Documents\Arduino\libraries\HomeKit-ESP8266\src\accessories.c line 395
0x40202644: cJSON_GetObjectItem at C:\Users\semte\Documents\Arduino\libraries\HomeKit-ESP8266\src\cJSON.c line 1823
0x40217f3c: process_characteristics_update(cJSON const*, _client_context_t*) at C:\Users\semte\Documents\Arduino\libraries\HomeKit-ESP8266\src\arduino_homekit_server.cpp line 2183
0x40100bcc: malloc(size_t) at C:\Users\semte\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\umm_malloc\umm_malloc.cpp line 552
0x40100913: umm_free_core(void*) at C:\Users\semte\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\umm_malloc\umm_malloc.cpp line 351
0x40100b97: free(void*) at C:\Users\semte\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\umm_malloc\umm_malloc.cpp line 398
0x40219ee0: homekit_server_on_update_characteristics(_client_context_t*, unsigned char const*, unsigned int) at C:\Users\semte\Documents\Arduino\libraries\HomeKit-ESP8266\src\arduino_homekit_server.cpp line 2402
0x4021b3d8: homekit_server_on_message_complete(http_parser*) at C:\Users\semte\Documents\Arduino\libraries\HomeKit-ESP8266\src\arduino_homekit_server.cpp line 2821
0x40204dd8: http_parser_execute at C:\Users\semte\Documents\Arduino\libraries\HomeKit-ESP8266\src\http_parser.c line 1928
0x40100bcc: malloc(size_t) at C:\Users\semte\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\umm_malloc\umm_malloc.cpp line 552
0x4021a119: homekit_client_process(_client_context_t*) at C:\Users\semte\Documents\Arduino\libraries\HomeKit-ESP8266\src\arduino_homekit_server.cpp line 2938
0x4021a3aa: homekit_server_process(homekit_server_t*) at C:\Users\semte\Documents\Arduino\libraries\HomeKit-ESP8266\src\arduino_homekit_server.cpp line 3120
0x40224141: __delay(unsigned long) at C:\Users\semte\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\core_esp8266_wiring.cpp line 57
0x4021b6e5: arduino_homekit_loop() at C:\Users\semte\Documents\Arduino\libraries\HomeKit-ESP8266\src\arduino_homekit_server.cpp line 3570
0x40216da6: homekit_loop() at C:\Users\semte\Documents\Arduino\libraries\HomeKit-ESP8266\examples\window_covering/window_covering.ino line 148
0x40216dbd: loop() at C:\Users\semte\Documents\Arduino\libraries\HomeKit-ESP8266\examples\window_covering/window_covering.ino line 107
0x40223c00: loop_wrapper() at C:\Users\semte\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\core_esp8266_main.cpp line 197`

**here is a serial:**

` [ 104260] HomeKit: Got new client: local 192.168.0.52:5556, remote 192.168.0.185:54455
>>> [ 104301] HomeKit: [Client 1073682044] Pair Setup Step 1/3
>>> [ 113589] HomeKit: [Client 1073682044] Pair Setup Step 2/3
>>> [ 113600] HomeKit: Call s_mp_exptmod in integer.c, original winsize 6
>>> [ 122481] HomeKit: Call s_mp_exptmod in integer.c, original winsize 5
>>> [ 127026] HomeKit: [Client 1073682044] Pair Setup Step 3/3
>>> [ 127056] HomeKit: Call ge_double_scalarmult_vartime_lowmem in ge_low_mem.c
>>> [ 127809] HomeKit: Added pairing with 0061BCB1-CF92-47F1-85F2-E0FE88B1EE0D
>>> [ 127882] HomeKit: Free saved_preinit_pairing_context
>>> [ 127887] HomeKit: [Client 1073682044] Successfully paired
>>> [ 128104] HomeKit: [Client 1073682044] Disconnected!
>>> [ 128109] HomeKit: [Client 1073682044] Closing client connection
>>> [ 128327] HomeKit: Got new client: local 192.168.0.52:5556, remote 192.168.0.185:54456
>>> [ 128337] HomeKit: [Client 1073682020] Pair Verify Step 1/2
>>> [ 128659] HomeKit: Free heap: 42544
>>> [ 128846] HomeKit: [Client 1073682020] Pair Verify Step 2/2
>>> [ 128852] HomeKit: [Client 1073682020] Found pairing with 0061BCB1-CF92-47F1-85F2-E0FE88B1EE0D
>>> [ 128876] HomeKit: Call ge_double_scalarmult_vartime_lowmem in ge_low_mem.c
>>> [ 129639] HomeKit: [Client 1073682020] Verification successful, secure session established
>>> [ 129648] HomeKit: Free heap: 42656
>>> [ 129803] HomeKit: [Client 1073682020] Get Accessories
>>> [ 129892] HomeKit: [Client 1073682020] Update Characteristics
>>> [ 129933] HomeKit: [Client 1073682020] Update Characteristics
>>> [ 129974] HomeKit: [Client 1073682020] Update Characteristics
>>> [ 130016] HomeKit: [Client 1073682020] Get Characteristics
>>> [ 140407] HomeKit: [Client 1073682020] Update Characteristics
nahoru
0
0
>>> [ 140424] HomeKit: [Client 1073682020] Got characteristic 1.10 change event
>>> [ 140431] HomeKit: [Client 1073682020] Got characteristic 1.8 change event
nahoru
1
1
>>> [ 140448] HomeKit: [Client 1073682020] Got characteristic 1.10 change event
>>> [ 140455] HomeKit: [Client 1073682020] Got characteristic 1.8 change event
nahoru
2
1
.
.
.
.
>>> [ 146128] HomeKit: [Client 1073682020] Got characteristic 1.10 change event
>>> [ 146135] HomeKit: [Client 1073682020] Got characteristic 1.8 change event
nahoru
233
1

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Soft WDT reset

>>>stack>>>

ctx: cont
sp: 3ffffbc0 end: 3fffffc0 offset: 01a0
3ffffd60:  40222858 00000001 00000002 40100499  
3ffffd70:  40100470 3ffef4fc 00000008 4021d716  
3ffffd80:  3ffef53c 00000007 3ffef4fc 4021d750  
3ffffd90:  3ffef53c 3ffef634 3ffef634 0000013f  
3ffffda0:  3ffef53c 3ffef634 3ffef534 40216e8e  
3ffffdb0:  00000000 00000000 7ace1faa 3fff0c14  
3ffffdc0:  00000000 00000001 3ffe8828 40216f44  
3ffffdd0:  000037f0 000006fe 000006fe 40100913  
3ffffde0:  facec499 00000001 00000000 40216294  
3ffffdf0:  00003704 3fff0c14 00000603 40202644  
3ffffe00:  00000021 00000104 3ffe8828 40217f3c  
3ffffe10:  3fff077c 00000001 00000020 40100bcc  
3ffffe20:  00000000 3fff10e4 3fff1704 00000000  
3ffffe30:  00003704 000006fe 00000603 40100913  
3ffffe40:  00000001 00000009 00000000 40080000  
3ffffe50:  00000000 00000000 3fff077c 00000000  
3ffffe60:  00000000 40590000 3fff340c 40100b97  
3ffffe70:  3fff1734 3fff0c14 00000000 00000000  
3ffffe80:  3fff1734 3fff0c14 00000000 40219ee0  
3ffffe90:  3fff1704 3fff157c 3fff087c 3fff077c  
3ffffea0:  00000004 00000000 0000000a 0000007b  
3ffffeb0:  3fff08d5 3fff1014 3fff0c14 4021b3d8  
3ffffec0:  3fff08d5 00040000 3fff104c 40204dd8  
3ffffed0:  3fff0824 3ffef54c 00000000 00000000  
3ffffee0:  00000000 00000000 00000000 3fff08d6  
3ffffef0:  000000b2 00000000 00000048 00000000  
3fffff00:  00000030 3fff088e 00000020 40100bcc  
3fffff10:  00000001 3ffef5a4 3fff1850 3ffef584  
3fffff20:  3fff0824 3fff0824 3fff0c14 4021a119  
3fffff30:  000000b2 53e36d44 02aa3000 00000000  
3fffff40:  000000b2 02aa5757 3ffef728 3ffef6c8  
3fffff50:  3fffdad0 00000000 3ffef5a4 3ffef6c8  
3fffff60:  3fffdad0 3ffefe24 3fff1014 4021a3aa  
3fffff70:  40224141 00000000 3ffef580 4021b6e5  
3fffff80:  00000000 00000000 3ffef688 40216da6  
3fffff90:  3fffdad0 00000000 3ffef688 40216dbd  
3fffffa0:  feefeffe feefeffe feefeffe 40223c00  
3fffffb0:  feefeffe feefeffe 3ffe8944 40100e51  
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 3584, room 16 
tail 0
chksum 0xb0
csum 0xb0
v2843a5ac
~ld`

**And here is my code: **

`#include <Arduino.h>
#include <arduino_homekit_server.h>
#include "wifi_info.h"
#include <Stepper_28BYJ_48.h>
#define LOG_D(fmt, ...)   printf_P(PSTR(fmt "\n") , ##__VA_ARGS__);

static int position_state = 0;          //Direction of blind (0 = down, 2 = stop, 1 = up)                 
static int targPos = 0;
static int path = 0;                     //Direction of blind (1 = down, 0 = stop, -1 = up)
static int current_position = 0;        //Current position of the blind
#define maxPosition 10660        //Max position of the blind. Initial value
bool ccw = true; 
Stepper_28BYJ_48 small_stepper(D1, D2, D3, D4);
	
	
	void setup() {
		Serial.begin(115200);
		wifi_connect();
		homekit_setup();
	}
	
	void loop() {
		homekit_loop();
		delay(10);
	}

	extern "C" homekit_server_config_t config; 
	extern "C" homekit_characteristic_t cha_current_position;
	extern "C" homekit_characteristic_t cha_target_position;
	extern "C" homekit_characteristic_t cha_position_state;

	void cha_target_position_setter(const homekit_value_t value) {
		uint8_t pos = value.int_value;
		cha_target_position.value.int_value = pos;
    targPos=pos;
    
    UpdatePosition();
	}
  void cha_position_state_setter(const homekit_value_t value) {
		uint8_t state = value.int_value;
		cha_position_state.value.int_value = state;
    homekit_characteristic_notify(&cha_position_state, cha_position_state.value);
    
    UpdatePosition();
	}
  void cha_current_position_setter(const homekit_value_t value) {
		uint8_t current_position = value.int_value;
		cha_current_position.value.int_value = current_position;
    homekit_characteristic_notify(&cha_current_position, cha_current_position.value);
    
    UpdatePosition();
	}
	void homekit_setup() {
		cha_target_position.setter=cha_target_position_setter;
    cha_position_state.setter=cha_position_state_setter;
    cha_current_position.setter=cha_current_position_setter;

		arduino_homekit_setup(&config);
	}

	void homekit_loop()	{
    delay(10);
		arduino_homekit_loop();
    delay(10);
	}
	
	void UpdatePosition(){
    int pos = 106.6*targPos;
    while (pos != current_position)
    {
      if (current_position>pos)
    { Serial.println("dolů");
      Serial.println(current_position);
      Serial.println(position_state);
      small_stepper.step(-1);
      current_position = current_position - 1;
      position_state = 0;  
      homekit_characteristic_notify(&cha_position_state, cha_position_state.value);
      homekit_characteristic_notify(&cha_current_position, cha_current_position.value);

    }else if(current_position<pos){
      Serial.println("nahoru");
      Serial.println(current_position);
      Serial.println(position_state);
      small_stepper.step(1);
      current_position = current_position + 1;
      position_state = 1;
      homekit_characteristic_notify(&cha_position_state, cha_position_state.value);
      homekit_characteristic_notify(&cha_current_position, cha_current_position.value);
    }
    
    
    }
    position_state = 2;
    Serial.println(position_state);
    digitalWrite(D1, LOW);
    digitalWrite(D2, LOW);
    digitalWrite(D3, LOW);
    digitalWrite(D4, LOW);
    homekit_characteristic_notify(&cha_position_state, cha_position_state.value);
    homekit_characteristic_notify(&cha_current_position, cha_current_position.value);
  }
  `
Can you please help me where is the problem ?

**Comment by edouardmenayde** [comment]
Hey, were you able to solve this ?

**Comment by Izac9** [comment]
> Hey, were you able to solve this ?

Hi, I solved my problem. I created code where you don't use WHILE but instead of while you use IF.
