### ISSUE TITLE
Update Question

### ISSUE THREAD

**Issue by HerbOtto** [Mixiaoxiao/Arduino-HomeKit-ESP8266#114]
Whenever I make a minor change to the code and re-upload it to the ESP8266 I need to remove and add the bridge back to HomeKit.  Is there a way to avoid doing this [and use the existing HK configuration]?  I am using a bridge with 6 shades (window covers).

**Comment by HerbOtto** [comment]
Found the issue - I was writing to location 0 -> 44 of the EEPROM which must have trashed HK IDs.  Moved to 2048 it seems stable.

*closed*

**Comment by korgoth** [comment]
@HerbOtto could you ellaborate on this one? How can you upload a new version to the device without erasing the EEPROM where HK ID is stored?
