### ISSUE TITLE
Switching to other device

### ISSUE THREAD

**Issue by tk97tk** [Mixiaoxiao/Arduino-HomeKit-ESP8266#118]
I wanted to switch the ui from a usual lightbulb to a TV ui. So i have changed the the **.category** of the **HOMEKIT_ACCESSORY** from **homekit_accessory_category_lightbulb** to **homekit_accessory_category_television**.

Now in my home app, it shows the tv UI and I can activate the device through a long press and a repeat press. Everything works fine. The TV turns on. 
Unfortunately, the button says updating all the time and I can not do a short tap to activate the device. 
Where I have to change something, to remove the updating?

![Screenshot 2021-02-23 at 18 32 10](https://user-images.githubusercontent.com/33938335/108883207-7254b480-7605-11eb-9ed3-4ed04567855d.png)

<img src="https://user-images.githubusercontent.com/33938335/108882130-57ce0b80-7604-11eb-97ca-d3cf3a132bf6.PNG"  width="200" height="400">
<img src="https://user-images.githubusercontent.com/33938335/108882608-e0e54280-7604-11eb-850d-8d6c40139ad8.PNG" width="200" height="400">
<img src="https://user-images.githubusercontent.com/33938335/108882949-2b66bf00-7605-11eb-961f-13af2b832afe.PNG" width="200" height="400">

**Comment by ApplebaumIan** [comment]
How are you checking whether the device is on or off?

**Comment by tk97tk** [comment]
I have used the default project simplest_led for testing

**Comment by ApplebaumIan** [comment]
So I think what's going on is that Homekit needs more than just on or off for a TV characteristic state. It could be something like "playing" or "not playing". I can't seem to find tv in Apple's HAP protocol docs.

**Comment by tk97tk** [comment]
The missing part is the port for choosing between the inputs (HMDI ...) for the tv, which I don't need 😅. The perfect solution would be a dummy function.

**Comment by awasspl** [comment]
Regarding HAP 
TV Category need television_service not lightbulb see You code. You mix accessory. HK get information that it's a TV accessory and you send light services with ON/off charactersitic.

Update definion:
1) TV category
2) TV service (not lightbulb)
3)  Required Characteristics for TV service (you have to add and updates them all to work properly)
 - ACTIVE
 - ACTIVE_IDENTIFIER
 - CONFIGURED_NAME
 - SLEEP_DISCOVERY_MODE
 
Optional:
 - IDENTIFIER
 - INPUT_DEVICE_TYPE
 - TARGET_VISIBILITY_STATE

**Comment by ApplebaumIan** [comment]
I also can't seem to recreate the issue. My ESP8266 shows up as a lightbulb. lol

**Comment by tk97tk** [comment]
@ApplebaumIan Yeah, you have to add television instead of lightbulb in the HOMEKIT_SERVICE. 

@awasspl  I also found this in the characteristics.h. But I have no clue how to initialized it probably. 
There is at least no compile error.
I have added them to the HOMEKIT_SERVICE.


![Screenshot 2021-02-25 at 00 19 12](https://user-images.githubusercontent.com/33938335/109079527-57ff0180-76ff-11eb-9c7d-478bfd9d23c8.png)
![Screenshot 2021-02-25 at 00 19 59](https://user-images.githubusercontent.com/33938335/109079540-5d5c4c00-76ff-11eb-87c8-7ffdb9d98811.png)

**Comment by awasspl** [comment]
First remove led_on characteristic becouse it's not support is TV servise
next You need to add all Required:

HOMEKIT_CHARACTERISTIC_(ACTIVE,0)
HOMEKIT_CHARACTERISTIC_(ACTIVE_IDENTIFIER,"")

**Comment by tk97tk** [comment]
Yeah, it's working, I added the methods to query the state of the homekit_format_uint8. I can now control my tv.

**Comment by hitenlulla** [comment]
@tk97tk Hello bro, Can you share your code? I'm trying to do it but it doesn't work. It'll be a great help. Thank you.
