### ISSUE TITLE
Redundant function from Example03 in Example04?

### ISSUE THREAD

**Issue by hpencilb** [Mixiaoxiao/Arduino-HomeKit-ESP8266#125]
https://github.com/Mixiaoxiao/Arduino-HomeKit-ESP8266/blob/592b4273e2b4d5eff378ab10738c6667c64c5161/examples/Example04_MultipleAccessories/Example04_MultipleAccessories.ino#L62-L66

Are these lines from Example03? Are they necessary when setting up multiple accessories?

**Comment by Mixiaoxiao** [comment]
You are right. These lines are from Example03, they are redundant.
