### ISSUE TITLE
Device incompatible

### ISSUE THREAD

**Issue by andyKien** [Mixiaoxiao/Arduino-HomeKit-ESP8266#129]
Hi,

i basically used your temperature sensor example, but replaced it by an ambient light sensor.
The device is showing up in the home app, but when I try to connect it says the device is incompatible.
(I even tried with your exact example)

Im using a Node MCU V2 (ESP8266MOD)

Is there any known compatibility issue with this device?

best regards

**Comment by Mixiaoxiao** [comment]
Accessory defination is invalid, or value is out of range. Check HAP doc.

**Comment by andyKien** [comment]
Hi,

thanks for the response. 
After showing multiple different errors it randomly startet to be able to connect and also transmit data.

Unfortunately it is recognized as a light, instead of a sensor, despite setting the category to sensor ".category=homekit_accessory_category_sensor".
