### ISSUE TITLE
请问单独按键回调函数在哪里

### ISSUE THREAD

**Issue by tsk15535904190** [Mixiaoxiao/Arduino-HomeKit-ESP8266#13]
我找不到按键回调函数

**Comment by Mixiaoxiao** [comment]
你可以自己写

**Comment by tsk15535904190** [comment]
> 你可以自己写

请问人体传感器的io引脚是哪个？

**Comment by Mixiaoxiao** [comment]
This is a "virtual" occupancy sensor in the example simple_led.
示例中的人体传感器是“虚拟的”，仅用于展示相关API的用法。
