### ISSUE TITLE
unable to add accessory

### ISSUE THREAD

**Issue by RudraR20** [Mixiaoxiao/Arduino-HomeKit-ESP8266#133]
hi sir this project is really awesome but i am having some error . actually i can the see the esp in my homekit app but as soon as i try to log into it its says unable to add accessory . sir please help me . and i am attaching some file please check it 

>![WhatsApp Image 2021-06-24 at 1 48 39 PM](https://user-images.githubusercontent.com/81382826/123259672-5d842100-d512-11eb-9f8a-1b788577577e.jpeg)
  
>![WhatsApp Image 2021-06-24 at 1 49 06 PM](https://user-images.githubusercontent.com/81382826/123259807-89070b80-d512-11eb-9f86-601842eefd7a.jpeg) 

>https://user-images.githubusercontent.com/81382826/123260430-2c582080-d513-11eb-9962-4d2c54aa52c1.mp4

 please reply as soon as possible

**Comment by hassbian-ABC** [comment]
IOS15?

**Comment by RudraR20** [comment]
ya

**Comment by hassbian-ABC** [comment]
The problem with IOS 15 is very good on IOS 14

**Comment by moonshot87** [comment]
Up. Having same problem

**Comment by moonshot87** [comment]
> The problem with IOS 15 is very good on IOS 14

Any workaround?

**Comment by RudraR20** [comment]
try to do on a raspberry pi

**Comment by RudraR20** [comment]
it is much simpler

**Comment by RudraR20** [comment]
and if you wanna do with esp with homekit i have a easy solution

**Comment by RudraR20** [comment]
first of all download home assistant on any platform like windows , mac , raspberry pi . Then compile the this particular code to your esp module . Then download homekit controller on home assistant .  then download home kit on home assistant and scan . you will get you result

**Comment by RudraR20** [comment]
if any problem contact - rudrarajputsingh1040@gmail.com

**Comment by hassbian-ABC** [comment]
> first of all download home assistant on any platform like windows , mac , raspberry pi . Then compile the this particular code to your esp module . Then download homekit controller on home assistant . then download home kit on home assistant and scan . you will get you result

Oh no, using Arduino-Homekit-ESP8266 is to simplify the problem. You make the problem more complicated

**Comment by RudraR20** [comment]
you think so

**Comment by RudraR20** [comment]
i AM just 14 so if i can do then maybe you can do that too

**Comment by RudraR20** [comment]
give it a try

**Comment by RudraR20** [comment]
and I recommend to use a raspberry pi it is much much much more easy and can use 16 channel relay

**Comment by hassbian-ABC** [comment]
> give it a try

No, Homeassistant is a cluttered platform that I gave up two years ago

**Comment by moonshot87** [comment]
Do you have any sample of working code?

**Comment by moonshot87** [comment]
> give it a try 
> 
> 

Do you have any sample of working code?

**Comment by hassbian-ABC** [comment]
I prefer to use homebridge

**Comment by RudraR20** [comment]
> > give it a try
> 
> No, Homeassistant is a cluttered platform that I gave up two years ago

THEN use homebridge

**Comment by RudraR20** [comment]
> I prefer to use homebridge

you can use

**Comment by RudraR20** [comment]
> > give it a try
> 
> Do you have any sample of working code?

this is too simple

**Comment by RudraR20** [comment]
do you guys have a raspberry pi ??
any model will work

**Comment by RudraR20** [comment]
its simple

**Comment by RudraR20** [comment]
and guys i have my own voice assistant named  jarvis

**Comment by hassbian-ABC** [comment]
This is a bug on IOS 15. There's no need to do anything unnecessary

**Comment by RudraR20** [comment]
broo i have 3 iphone

**Comment by RudraR20** [comment]
one with ios 15 and other with ios 14

**Comment by RudraR20** [comment]
i have tried

**Comment by RudraR20** [comment]
and i am just recommending the other way with is more easy according to me

**Comment by RudraR20** [comment]
where are you from ??

**Comment by PR77** [comment]
> This is a bug on IOS 15. There's no need to do anything unnecessary

Is this really an IOS 15 bug or has something changed where the pairing times are enforced? I made several homekit devices and recently I had to remove one device and re-pair but this did not work unfortunately. After a lot of research, it seems IOS 15.x introduced a forced pairing time which the ESP8266 can't achieve.

**Comment by devangs3** [comment]
Reporting same issue on iOS 16.1 beta 
![Screenshot 2022-10-22 01 18 23](https://user-images.githubusercontent.com/14045070/197328863-9fc27559-d44e-4bd8-8e07-81d808705097.png)
![WhatsApp Image 2022-10-22 at 1 21 58 AM (1)](https://user-images.githubusercontent.com/14045070/197328905-46b0baca-3053-4451-bacd-bc8a6b5ee7a0.jpeg)
![WhatsApp Image 2022-10-22 at 1 21 58 AM](https://user-images.githubusercontent.com/14045070/197328906-48fd97f7-1e1d-4e9c-932d-cad0922f33fd.jpeg)
![WhatsApp Image 2022-10-22 at 1 21 57 AM (1)](https://user-images.githubusercontent.com/14045070/197328908-07f0d4d4-18e2-4a4b-a592-1f2908c872ff.jpeg)
![WhatsApp Image 2022-10-22 at 1 21 57 AM](https://user-images.githubusercontent.com/14045070/197328910-a356a0c6-4278-49d6-90cc-608450821b3c.jpeg)
