### ISSUE TITLE
Multiple homekit accessories on one ESP8266

### ISSUE THREAD

**Issue by izandotnet** [Mixiaoxiao/Arduino-HomeKit-ESP8266#153]
I’m not sure how to ask this correctly.

Is it possible, for example, 2 switches connected to a single ESP8266 module, and make it appear as 2 different accessories in my Iphone?

Thanks

**Comment by Mixiaoxiao** [comment]
Example04_MultipleAccessories

**Comment by izandotnet** [comment]
Really appreciate your response @Mixiaoxiao 
Thank you.
