### ISSUE TITLE
do not compile

### ISSUE THREAD

**Issue by AugustinMauroy** [Mixiaoxiao/Arduino-HomeKit-ESP8266#172]
Arduino-HomeKit-ESP8266-master/examples/legacy/simple_led/simple_led_accessory.c: In function 'led_update':
simple_led_accessory.c:67:13: error: 'PWMRANGE' undeclared (first use in this function)
   67 |   int pwm = PWMRANGE - (int) (led_bri * 1.0 * PWMRANGE / 100.0 + 0.5f);

**Comment by kuznetsov-m** [comment]
This issue has nothing to do with this project. However, I decided to try redefining the PWMRANGE variable.
I just added a declaration int PWMRANGE = 1023; to the method [led_update()](https://github.com/Mixiaoxiao/Arduino-HomeKit-ESP8266/blob/master/examples/legacy/simple_led/simple_led_accessory.c#L65-L74)

https://github.com/Mixiaoxiao/Arduino-HomeKit-ESP8266/issues/162

**Comment by AugustinMauroy** [comment]
thanks
