### ISSUE TITLE
device no response, serial monitor find 0 clients

### ISSUE THREAD

**Issue by loujiabin** [Mixiaoxiao/Arduino-HomeKit-ESP8266#181]
esp8266 works perfect once it connected in the beginning, but after several days, it will lost connections. just like those son-off devices i bought from TaoBao.
try to change modem settings such as , use certain channel, 2.4g only... the good news is: son-off devices never lose connections after i configure modem. but esp8266 still no response after a few weeks. 
on esp8266 serial monitor, it saids: free heap: 42448, homekit clients:0

any suggestion what command i should use in serial monitor to figure our the problem?

**Comment by mrthiti** [comment]
I would like to try something. Can you try turn off modem and then turn on again please. I think it not work after that.

So, I think it is problem of the issue.

**Comment by L2Miko** [comment]
Same problem. It will lost control after a few days or weeks. Always clients:0. The only way is to turn off and turn on. unstable than son-off firmware.

**Comment by mrthiti** [comment]
@L2Miko I create PR (https://github.com/Mixiaoxiao/Arduino-HomeKit-ESP8266/pull/184) for fix that issue.
Any way, You can try edit code follow PR in your local, I think is solve the issue. that it work for me.

**Comment by loujiabin** [comment]
Problem solved.
Found from other comments.
Erase mDNS restart from lib file then no more connection lose

**Comment by blahBlahhhJ** [comment]
Sorry. I can't seem to find any code related to "mDNS restart" from the library. Do you mean this code block?
```
if (homekit_mdns_started) {
  MDNS.close();
  MDNS.begin(name->value.string_value, staIP);
  INFO("MDNS restart: %s, IP: %s", name->value.string_value, staIP.toString().c_str());
  MDNS.announce();
  return;
}
```
and should the entire block be deleted?

**Comment by loujiabin** [comment]
No,  only erase this line

> MDNS.close();
> 
It’s under library file which i cant remember the name.

**Comment by blahBlahhhJ** [comment]
thanks! works like a charm, at least for now.
