### ISSUE TITLE
Accssory shows as "No Response"

### ISSUE THREAD

**Issue by korgoth** [Mixiaoxiao/Arduino-HomeKit-ESP8266#194]
Hey guys

Im trying to make a NodeMCU based AC controller using this library and the IRRemoteESP8266 Library. The "THERMOSTAT" accessory seems to be a great fit for this. 

I have everything setup and working: 
- the Accessory pairs with the home app
- all the controls seem to be working and sending correct IR signals
- i have also hooked up a temperature sensor which is reporting every 10 seconds (i have tried various times) and even that notification to homekit seems to be working great.

However quite often my accessory shows as "No response" in the Home App dashboard (or even in the accessory details). Its very random, and i can not get any pattern out of it. Sometimes its when i kill the home app and reopen it. Other times it will be while its still open. Funny thing is - while the accessory is not responding - if i force change some of the controls (IE change from OFF to HEAT, or COOL) - the NodeMCU is actually sending the IR Signal and my AC is controlled (that only works for modes, since the temperature dial is completely disabled in the home app when the accessory is shown as "no response"). 

I have read quite a while all over various forums about the "no response" issue and in my desperation have tried various things: 
- reporting some characteristic very often
- making a MDNS.announce() call every 5 seconds
- pinging the NodeMCU from the outside constantly 
but nothing seems to be working. 

I have enabled homekid debugging in this app (which produces a literally ton of messages) and checked the logs - i cant see a single line connected to that issue or even giving a warning about anything being abnormal. 
The only change that i notices after enabling the debugging is that if my accessory shows as "No resopnse" in the dashboard, if i click on it to enter the details it actually updates its state and the Home app dashboard and eveyrthing seems to be fine. After a while it just randomly goes to no resp again. 

I am attaching my code from Arduino IDE because it is quite long to paste here. 

If anyone has any experience with fighting this or can notice anything in my code that might be the reason for this behavior - please show me where i am wrong because i am going mad :D 

Any help is much appreciated!

[ARDUINO-IR-AC.zip](https://github.com/Mixiaoxiao/Arduino-HomeKit-ESP8266/files/9952925/ARDUINO-IR-AC.zip)

**Comment by ming-chu** [comment]
Maybe related to this issue #181
