### ISSUE TITLE
Recently found a conflicting library, causing it to not run properly

### ISSUE THREAD

**Issue by CHNleing** [Mixiaoxiao/Arduino-HomeKit-ESP8266#2]
[WiFiManager](https://github.com/tzapu/WiFiManager/tree/development#on-demand-configuration-portal)

**Comment by Mixiaoxiao** [comment]
The reason is that the `HTTP_METHOD` (eg `HTTP_GET` , `HTTP_POST`) is multi-defined in `ESP8266WebServer` library (used in WiFiManager) and `http_parser.h` of this library. I will change the definitions in `http_parser.h` in next version to make it compatible with `ESP8266WebServer`.

**Comment by Mixiaoxiao** [comment]
Hi, please check v1.0.1

**Comment by CHNleing** [comment]
> 嗨，请检查v1.0.1

Thank you, I will update now.

**Comment by CHNleing** [comment]
I suggest that you can make examples simpler and remove the physical keys. This makes it easier for novices to understand it

**Comment by euler271** [comment]
@CHNleing I will work on a simpler example over the weekend and make a pull request for it afterwards.
