### ISSUE TITLE
你好，我想知道关于配网的方法

### ISSUE THREAD

**Issue by tsk15535904190** [Mixiaoxiao/Arduino-HomeKit-ESP8266#20]
我尝试使用WiFiManager进行web配网，第一次可以正常接入，但是 在8266重启之后  保存wifi与密码功能不能使用，又得从新进行配网，我该怎么办，或许请告诉我更好的配网方式，谢谢

**Comment by Mixiaoxiao** [comment]
删掉本项目例子中的WiFi.persistent(false);这一行。
具体可以查阅ESP8266的官方文档。
