### ISSUE TITLE
EEPROM on ESP8266 will be restore after arduino_homekit_setup

### ISSUE THREAD

**Issue by super617** [Mixiaoxiao/Arduino-HomeKit-ESP8266#227]
Hi there：
I found an issue on this lib， when i store my WiFi SSID and password on EEPROM ,the API named **arduino_homekit_setup** will write all the EEPROM with '0xff' ,  Seems  of [1408, 4096) is not safe to use too, please help me to check this ,thanks!!

**Comment by ghost** [comment]
I already fixed it for myself over a year ago

**Comment by adityapal-singh-chauhan** [comment]
yes i also found this out the hard way the eeprom is not safe for use, coz of one function that formats the entire eeprom if the stored pairing key is not recovered, i recommend using littleFS, it will solve all your problems

**Comment by super617** [comment]
Thanks I will try littleFS instead
