### ISSUE TITLE
Interpreting negative integer values

### ISSUE THREAD

**Issue by jmbwell** [Mixiaoxiao/Arduino-HomeKit-ESP8266#34]
I'm getting unexpected values when HomeKit is supposedly sending me a negative integer. I am building a window covering that supports a horizontal tilt angle of between -90 and +90 degrees; when the values are positive, the values are correct, but when the values are supposed to be negative, they are working down from 255.

This strikes me as a two's complement conversion problem, but I can't figure out where the error is introduced, and I'm not sure whether I can deal with it in my code.

In my .getter function in the .ino file, I have this:
```
// Called when setting horizontal tilt position
void cha_target_horizontal_tilt_angle_setter(const homekit_value_t value) {
	int angle = value.int_value;
	cha_target_horizontal_tilt_angle.value.int_value = angle;
	LOG_D("Window covering horizontal tilt angle: %i (%i)", angle, value.format);

	// tell the servo (range 0 to 180) to go to the requested angle (range -90 to 90)
	angle = map(angle, -90, 90, 0, 180);
	LOG_D("Window covering horizontal tilt mapped angle: %i", angle);
	tiltServo.write(angle); 
}
```
But here's what I see in my logs when that function runs and I start moving the control slider to the left, which is supposedly sending negative values:
```
>>> [  38883] HomeKit: [Client 1073679940] Update Characteristics
Window covering horizontal tilt angle: 253 (5)
Window covering horizontal tilt mapped angle: 343
```

One of the relevant characteristics is HOMEKIT_CHARACTERISTIC_TARGET_HORIZONTAL_TILT_ANGLE in characteristics.h at line 1510, but the .format is int, which is expected.

```
#define HOMEKIT_CHARACTERISTIC_TARGET_HORIZONTAL_TILT_ANGLE HOMEKIT_APPLE_UUID2("7B")
#define HOMEKIT_DECLARE_CHARACTERISTIC_TARGET_HORIZONTAL_TILT_ANGLE(_value, ...) \
    .type = HOMEKIT_CHARACTERISTIC_TARGET_HORIZONTAL_TILT_ANGLE, \
    .description = "Target Horizontal Tilt Angle", \
    .format = homekit_format_int, \
    .unit = homekit_unit_arcdegrees, \
    .permissions = homekit_permissions_paired_read \
                 | homekit_permissions_paired_write \
                 | homekit_permissions_notify, \
    .min_value = (float[]) {-90}, \
    .max_value = (float[]) {90}, \
    .min_step = (float[]) {1}, \
    .value = HOMEKIT_INT_(_value), \
    ##__VA_ARGS__

```

And in arduino_homekit_server.cpp, starting at line 303, it appears to be correctly formatting the json string from the iOS device into an int:
```
...
		case homekit_format_int:
			format_str = "int";
			break;
...
		if (format_str) {
			json_string(json, "format");
			json_string(json, format_str);
		}
```

And in the homekit_value_copy function from accessories.c, at line 73, it seems to be just copying the int value…
```
            case homekit_format_int:
                dst->int_value = src->int_value;
                break;
```

But I'm coming to this for the first time, and so I'm not sure I'm even on the right path.

I'm also not sure this isn't something to do with ESP8266 handling signed integers. I don't know much about its internals. The board I'm on is a LoLin NodeMCU.

Any help would be appreciated… and I am likewise happy to help any way I can.

**Comment by Mixiaoxiao** [comment]
It is my mistake. In types.c line 26, change `homekit_value_t HOMEKIT_INT_CPP(uint8_t value) ` to `homekit_value_t HOMEKIT_INT_CPP(int value) `.
