### ISSUE TITLE
Conflicting base64 files name

### ISSUE THREAD

**Issue by ETblaky** [Mixiaoxiao/Arduino-HomeKit-ESP8266#37]
Hey, first of all I just want to say what a great project this is.
I also want to suggest changing the name of the files "base64.h" and "base64.cpp", as they already exist in the espressif8266 framework. I have been having some problems because of it, and I imagine other people may as well have.
If that's not a good idea, how could I choose which file to include? I'm using PlatformIO in my project.

**Comment by Mixiaoxiao** [comment]
Change the "base64.h/cpp" to "homekit_base64.h/cpp" or other names temporarily.
