### ISSUE TITLE
if i reboot the device it looses connection

### ISSUE THREAD

**Issue by antonioreyna** [Mixiaoxiao/Arduino-HomeKit-ESP8266#40]
when turn off and on the device, it looses teh connection to homekit  and im not able to see the data anymore, its a temperature sensor, also im using a wifi manager library called iotwebconfig and when homekit library is enabled, it also erase all data in eeprom from that library.

**Comment by Mixiaoxiao** [comment]
Do NOT touch the EEPROM of [0, 1408B), which is used by this library. If another library uses EEPROM too, you need to solve the conflict by yourself.

**Comment by Mixiaoxiao** [comment]
This is not an issue of this library, will be closed soon.

**Comment by antonioreyna** [comment]
fixed it thanks
