### ISSUE TITLE
提供一个修改建议

### ISSUE THREAD

**Issue by cmz97** [Mixiaoxiao/Arduino-HomeKit-ESP8266#45]
我发现，在使用您的temperature example的时候，第一次上传ESP8266一切正常，Homekit也可以pairing. 但是在手机上删除此元件后，再次重启ESP8266,  再想去pair，再也搜索不到。我为了绕过这个，就直接comment掉`server->paired = true` 

`	while (!homekit_storage_next_pairing(&pairing_it, &pairing)) {
		if (pairing.permissions & pairing_permissions_admin) {
			//INFO("Found admin pairing with %s, disabling pair setup", pairing.device_id);
      INFO("XXXXXXXXXX");
			// server->paired = true;
			break;
		}
	}`
为了永久的解决这个问题，whileloop里面是不是可以加一个flag，可以让user选择force paring。 可以避免这个问题。应为再homekit删除后， 直接force `server->paired = true` 就跳过了新的pairing机会。

这只是我想的一个办法，您看您有什么更好的办法解决这个问题也可以。
我想说您写的这个库真的很厉害，真的很帮助到我！ 感谢

**Comment by Mixiaoxiao** [comment]
[Refer to this: https://github.com/Mixiaoxiao/Arduino-HomeKit-ESP8266/issues/10#issuecomment-613969645](https://github.com/Mixiaoxiao/Arduino-HomeKit-ESP8266/issues/10#issuecomment-613969645)
