### ISSUE TITLE
Cannot add accessory based on ESP32

### ISSUE THREAD

**Issue by sto-chastic** [Mixiaoxiao/Arduino-HomeKit-ESP8266#48]
I was experimenting and I made a mistake in the `homekit_accessory_t *accessories[]` and Apple disconnected from the accessory when I tried to activate a switch. I corrected the error but now I cannot find the accessory anymore after inserting the "8-digit homekit setup code". Do you know how can I recover it?

**Comment by Mixiaoxiao** [comment]
Call `homekit_storage_reset()` to remove the saved pairing information. Or erase full Flash on your ESP.
Not an issuse and will be closed soon.

**Comment by sto-chastic** [comment]
thanks, that did the trick!
