### ISSUE TITLE
simple_led:95: error: expected initializer before 'btnInterrupt'

### ISSUE THREAD

**Issue by kindzhon** [Mixiaoxiao/Arduino-HomeKit-ESP8266#5]
请教：编译出这个错是咋回事？是不是8266的核心用的不对？我用的是2.4.2
simple_led:95: error: expected initializer before 'btnInterrupt'

void IRAM_ATTR btnInterrupt() {

**Comment by Mixiaoxiao** [comment]
把SDK更新到2.6.3(目前最新版本)可以编译通过。或者试试去掉IRAM_ATTR标记，该标记是强制这个函数放在IRAM分区，因为这是个中断回调函数。(可能旧版本的SDK还没有这个标记)

**Comment by kindzhon** [comment]
谢谢！所有的IRAM_ATTR都去掉啊？那工程量大的了，头文件中很多用这个。

**Comment by kindzhon** [comment]
试了不行，太多错误了。可能还得用最新版的。
