### ISSUE TITLE
Problem with connecting to the esp

### ISSUE THREAD

**Issue by Phenixdv** [Mixiaoxiao/Arduino-HomeKit-ESP8266#51]
HI,
I’m Having trouble with connecting to my ESP 32, I uploaded the switch example sketch provided,
but on the phone, it doesn’t show up to select to pair with it. (I also tried it with the Temperature sensor and it didn’t work either)
these are the messages I get from the ESP,
![image](https://user-images.githubusercontent.com/68974314/88863309-cd0a6700-d202-11ea-8a28-718f618db4a1.png)

it worked a few times before until I uncomment the command; `homekit_storage_reset()` and uploadet it.
In the message `>>> [ 343] HomeKit: Found admin pairing with A1D6497F-4683-49CF-935B-2321A9ABB508, disabling pair setup`
it says `disabling pair setup` I don’t know if that does mean anything but it doesn’t sound right to me that early.

**Comment by Mixiaoxiao** [comment]
The paired info is saved in Flash. You should call `homekit_storage_reset()` or erase the full flash before you upload a new project. The paired esp (which has paired info in Flash) will disable the new pair.
See [https://github.com/Mixiaoxiao/Arduino-HomeKit-ESP8266/issues/10#issuecomment-613969645](https://github.com/Mixiaoxiao/Arduino-HomeKit-ESP8266/issues/10#issuecomment-613969645)

**Comment by Phenixdv** [comment]
I did, I also flashed an empty scatch on the ESP but nothing changed.

**Comment by Mixiaoxiao** [comment]
Your `flashed an empty scatch(->sketch)` does **NOT** equal to `erase the full flash`. IDE settings `Erase Flash`: select All Flash Contents. Or use ESP flash tool to erase full flash.

**Comment by Phenixdv** [comment]
thanks for the help, I used the esp 32 download tool, to erase the full flash and it workes now!
