### ISSUE TITLE
Error platformio

### ISSUE THREAD

**Issue by Oktan89** [Mixiaoxiao/Arduino-HomeKit-ESP8266#53]
Good afternoon, I really like Your library on the Arduino IDE everything was fine, but I decided to use VSC. My code is the same as Yours with minor changes. Please help me. I can't compile the project in VSC PlatformIO. The compiler outputs the following errors:

My settings in platform.ini:
______________________________________________________________________________________________________________________________________
[env:esp01_1m]
platform = espressif8266
board = esp01_1m
framework = arduino
; Using a library HomeKit-ESP8266 (7045)
;Using a library name ESP8266FtpServer (992)
;Using a library name DHT sensor library (19)
lib_deps = 
 7045
 992 
 19
; set CPU frequency to 160MHz, to 80-Mhz 80000000L
board_build.f_cpu = 160000000L
; set FLASH frequency to 80MHz
board_build.f_flash = 80000000L
; set FLASH mode (qio, qoutm dio, dout)
board_build.flash_mode = qio
; Reset Method (ck, wifio, nodemcu)
upload_resetmethod = ck
; Flash Size https://github.com/esp8266/Arduino/tree/master/tools/sdk/ld
board_build.ldscript = eagle.flash.1m64.ld
;Upload Speed
upload_speed = 115200
;lwIP Variant
build_flags = -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY -D PIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK221 -D BEARSSL_SSL_BASIC -DNDEBUG -DVTABLES_IN_FLASH
_________________________________________________________________________________________________________________________________
> Executing task in folder esp8266DHT21: C:\Users\rzhig\.platformio\penv\Scripts\platformio.exe run <

Processing esp01_1m (platform: espressif8266; board: esp01_1m; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp01_1m.html
PLATFORM: Espressif 8266 2.6.2 > Espressif Generic ESP8266 ESP-01 1M
HARDWARE: ESP8266 160MHz, 80KB RAM, 1MB Flash
PACKAGES:
 - framework-arduinoespressif8266 3.20704.0 (2.7.4)
 - tool-esptool 1.413.0 (4.13)
 - tool-esptoolpy 1.20800.0 (2.8.0)
 - toolchain-xtensa 2.40802.200502 (4.8.2)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
LibraryManager: Installing id=7045
Using cache: C:\Users\rzhig\.platformio\.cache\2e\dd4ad81979d9bc876509cca35a118f2e
HomeKit-ESP8266 @ 1.2.0 has been successfully installed!
LibraryManager: Installing id=992
Using cache: C:\Users\rzhig\.platformio\.cache\da\d16f40f3b4c5f862ad6f7d70c5cf71da
esp8266FTPServer @ 1.0.1 has been successfully installed!
LibraryManager: Installing id=19
Using cache: C:\Users\rzhig\.platformio\.cache\bd\834944ae942986fabd8560ee9995cdbd
DHT sensor library @ 1.3.10 has been successfully installed!
Installing dependencies
Looking for Adafruit Unified Sensor library in registry
Found: https://platformio.org/lib/show/31/Adafruit Unified Sensor
LibraryManager: Installing id=31
Using cache: C:\Users\rzhig\.platformio\.cache\0b\e5cb7d3f156b54236879ddb31efac40b
Adafruit Unified Sensor @ 1.1.4 has been successfully installed!
Found 33 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <HomeKit-ESP8266> 1.2.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266mDNS> 1.2
|   |   |-- <ESP8266WiFi> 1.0
|-- <DHT sensor library> 1.3.10
|   |-- <Adafruit Unified Sensor> 1.1.4
|-- <esp8266FTPServer> 1.0.1
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <ESP8266WebServer> 1.0
|   |-- <ESP8266WiFi> 1.0
Building in release mode
Linking .pio\build\esp01_1m\firmware.elf
c:/users/rzhig/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: .pio\build\esp01_1m\src\main.cpp.o:(.text._Z16my_homekit_setupv+0x0): undefined reference to `config'
c:/users/rzhig/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: .pio\build\esp01_1m\src\main.cpp.o:(.text._Z17my_homekit_reportv+0x8): undefined reference to `cha_temperature'
c:/users/rzhig/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: .pio\build\esp01_1m\src\main.cpp.o:(.text._Z17my_homekit_reportv+0xc): undefined reference to `cha_status_temp_active'
c:/users/rzhig/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: .pio\build\esp01_1m\src\main.cpp.o:(.text._Z17my_homekit_reportv+0x10): undefined reference to `cha_status_temp_fault'
c:/users/rzhig/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: .pio\build\esp01_1m\src\main.cpp.o:(.text._Z17my_homekit_reportv+0x18): undefined reference to `cha_humidity'
c:/users/rzhig/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: .pio\build\esp01_1m\src\main.cpp.o:(.text._Z17my_homekit_reportv+0x1c): undefined reference to `cha_status_humi_active'
c:/users/rzhig/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: .pio\build\esp01_1m\src\main.cpp.o:(.text._Z17my_homekit_reportv+0x20): undefined reference to `cha_status_humi_fault'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\esp01_1m\firmware.elf] Error 1
======================================================================================================== [FAILED] Took 5.11 seconds ========================================================================================================
The terminal process "C:\Users\rzhig\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
_______________________________________________________________________________________________________________________________________
{
	"resource": "/c:/Users/rzhig/Documents/PlatformIO/Projects/esp8266DHT21/include/my_accessory.h",
	"owner": "C/C++",
	"severity": 8,
	"message": "a value of type \"int\" cannot be used to initialize an entity of type \"homekit_permissions_t\"",
	"startLineNumber": 25,
	"startColumn": 44,
	"endLineNumber": 25,
	"endColumn": 67
}
{
	"resource": "/c:/Users/rzhig/Documents/PlatformIO/Projects/esp8266DHT21/include/my_accessory.h",
	"owner": "C/C++",
	"severity": 8,
	"message": "a designator for an anonymous union member can only appear within braces corresponding to that anonymous union",
	"startLineNumber": 57,
	"startColumn": 5,
	"endLineNumber": 57,
	"endColumn": 22
}

**Comment by jgseric** [comment]
Hello,
I had the same issue. Solved when added the "HomeKit-ESP8266 library"
Bye
