### ISSUE TITLE
Push button switch.

### ISSUE THREAD

**Issue by marmitol** [Mixiaoxiao/Arduino-HomeKit-ESP8266#54]
Hello.

Thanks for project Arduino-HomeKit-ESP8266. 
I would need to create a push button switch. I have been trying the switch example, it works fine.
I need to automate a door opening by pressing it for about 3 seconds.
The problem with the example is that there are only two On/Off potions. I would need after about 3 seconds to go from the on state to the off state.

Thank you very much.

**Comment by Mixiaoxiao** [comment]
You should write your own logic code. The HomeKit is only a tool (with only two On/Off potions).

**Comment by marmitol** [comment]
Ok

thank
