### ISSUE TITLE
Fan service stuck in loading state

### ISSUE THREAD

**Issue by micampe** [Mixiaoxiao/Arduino-HomeKit-ESP8266#55]
I created a Fan service like this:

```cpp
homekit_characteristic_t ch_fan_active = HOMEKIT_CHARACTERISTIC_(ACTIVE, FAN_INACTIVE);
homekit_characteristic_t ch_fan_rotation_speed = HOMEKIT_CHARACTERISTIC_(ROTATION_SPEED, 10.0);
homekit_characteristic_t ch_fan_swing_mode = HOMEKIT_CHARACTERISTIC_(SWING_MODE, FAN_SWING_DISABLED);

homekit_service_t fan_service = HOMEKIT_SERVICE_(FAN, .primary = true,
    .characteristics = (homekit_characteristic_t *[]) {
        HOMEKIT_CHARACTERISTIC(NAME, "Fan"),
        &ch_fan_active,
        &ch_fan_rotation_speed,
        &ch_fan_swing_mode,
        NULL
    });
```

and the tile in the Home app is stuck in the “Loading” state and tapping it doesn't toggle the fan on.

If I expand the tile and toggle the big switch, the tile shows “On” and “Off” correctly, but it is still grey instead of highlighted with the spinning fan.

I have other services in the same accessory and those work as expected. Removing all the other services and just making a fan accessory has the same issue; removing all the characteristics except for active (the only required one) also stays stuck in “Loading”.

In my investigation I noticed that the `#define HOMEKIT_DECLARE_CHARACTERISTIC_ROTATION_SPEED` is not initialising the `.value` field (which seems a bug in itself, same issue for _ROTATION_DIRECTION), but adding that doesn't seem to fix the problem.

I believe I tried all the combinations and I’m now out of ideas. Let me know how I can assist in debugging this.

**Comment by micampe** [comment]
alright, replaced FAN with FAN2 and it works.

**Comment by micampe** [comment]
I haven't tested this theory but I believe the issue was that FAN uses an ON characteristic, while FAN2 uses ACTIVE.

**Comment by guangmin0622** [comment]
您好，可以分享您整個FAN的程式嗎?
