### ISSUE TITLE
Accessory limit for bridges?

### ISSUE THREAD

**Issue by thncode** [Mixiaoxiao/Arduino-HomeKit-ESP8266#74]
Is there a limit for the number of accessories per bridge? Whenever I try to add 4 accessories I do get exceptions in accessories.c / arduino_homekit_server.cpp...

Rgrds,
 Thomas

**Comment by Mixiaoxiao** [comment]
Something wrong in your code. There are 6 accessories in Example04. 
Not an issue, will be closed soon.

**Comment by thncode** [comment]
yes, but that is funny / strange: if I put 4 identical switch accessories into the bridge code it crashes, if I replace the 4th switch with e.g. a sensor, it works...

**Comment by Mixiaoxiao** [comment]
Check your code, the last accessory should be 'NULL'.

**Comment by thncode** [comment]
it is: I just replaced the crash inducing accessory switch with a sensor
