### ISSUE TITLE
Dual switch on one Device

### ISSUE THREAD

**Issue by xuanbka1** [Mixiaoxiao/Arduino-HomeKit-ESP8266#78]
Hi Mixiaoxiao, 
I try to add to component switch to one Device like picture,
Can I solve this problem ?
![image](https://user-images.githubusercontent.com/10722508/97151097-9f04d680-17a1-11eb-9eb6-8ced46b55ed6.jpeg)
Thanks for support !

**Comment by YaoGi** [comment]
of course I've used this library to control my lights

**Comment by xuanbka1** [comment]
I did it but homekit show two separate switch, and now i want to intergrate 2 switch on one device,
Can you help me ?
