### ISSUE TITLE
Storage base address?

### ISSUE THREAD

**Issue by thncode** [Mixiaoxiao/Arduino-HomeKit-ESP8266#83]
using EEPROM.h really "disturbs" the structure of this library. But what storage base address can I rely on? Is it this one:
#define STORAGE_BASE_ADDR 0x200000 
#define STORAGE STORAGE_BASE_ADDR + 1408

But this does not work...

Rgrds,
 Thomas

**Comment by Mixiaoxiao** [comment]
https://github.com/Mixiaoxiao/Arduino-HomeKit-ESP8266/issues/79#issuecomment-721092920
