### ISSUE TITLE
connect 2 different ws2812 strips to one esp

### ISSUE THREAD

**Issue by kefkevm** [Mixiaoxiao/Arduino-HomeKit-ESP8266#85]
hi,

i want use 2 strips on one esp.  i can pair on my iphone and see 2 sepperate lightbulbs tiles for controlling. but only the first one is working. the second strip dont react. what do i wrong in my code?

#include <homekit/homekit.h>
#include <homekit/characteristics.h>

void my_accessory_identify(homekit_value_t _value) {
  printf("accessory identify\n");
}

homekit_characteristic_t cha_on = HOMEKIT_CHARACTERISTIC_(ON, false);
homekit_characteristic_t cha_name = HOMEKIT_CHARACTERISTIC_(NAME, "ESP8266 Lamp");
homekit_characteristic_t cha_bright = HOMEKIT_CHARACTERISTIC_(BRIGHTNESS, 50);
homekit_characteristic_t cha_sat = HOMEKIT_CHARACTERISTIC_(SATURATION, (float) 0);
homekit_characteristic_t cha_hue = HOMEKIT_CHARACTERISTIC_(HUE, (float) 180);

      homekit_characteristic_t cha_on2 = HOMEKIT_CHARACTERISTIC_(ON, false);            // 2e strip
      homekit_characteristic_t cha_name2 = HOMEKIT_CHARACTERISTIC_(NAME, "ESP8266 Lamp2");
      homekit_characteristic_t cha_bright2 = HOMEKIT_CHARACTERISTIC_(BRIGHTNESS, 50);
      homekit_characteristic_t cha_sat2 = HOMEKIT_CHARACTERISTIC_(SATURATION, (float) 0);
      homekit_characteristic_t cha_hue2 = HOMEKIT_CHARACTERISTIC_(HUE, (float) 180);

homekit_accessory_t *accessories[] = {
    HOMEKIT_ACCESSORY(.id=1, .category=homekit_accessory_category_lightbulb, .services=(homekit_service_t*[]) {
        HOMEKIT_SERVICE(ACCESSORY_INFORMATION, .characteristics=(homekit_characteristic_t*[]) {
            HOMEKIT_CHARACTERISTIC(NAME, "ESP8266 Lamp"),
            HOMEKIT_CHARACTERISTIC(MANUFACTURER, "Arduino HomeKit"),
            HOMEKIT_CHARACTERISTIC(SERIAL_NUMBER, "0123456"),
            HOMEKIT_CHARACTERISTIC(MODEL, "ESP8266"),
            HOMEKIT_CHARACTERISTIC(FIRMWARE_REVISION, "1.0"),
            HOMEKIT_CHARACTERISTIC(IDENTIFY, my_accessory_identify),
            NULL
        }),
        HOMEKIT_SERVICE(LIGHTBULB, .primary=true, .characteristics=(homekit_characteristic_t*[]) {      
            &cha_on,
            &cha_name,
            &cha_bright,
            &cha_sat,
            &cha_hue,
            NULL
        }),
        NULL
    }),

    HOMEKIT_ACCESSORY(.id=2, .category=homekit_accessory_category_lightbulb, .services=(homekit_service_t*[]) {
        HOMEKIT_SERVICE(ACCESSORY_INFORMATION, .characteristics=(homekit_characteristic_t*[]) {
            HOMEKIT_CHARACTERISTIC(NAME, "ESP8266 Lampje2"),
            HOMEKIT_CHARACTERISTIC(IDENTIFY, my_accessory_identify),
            NULL
     }),
     HOMEKIT_SERVICE(LIGHTBULB, .characteristics=(homekit_characteristic_t*[]) {      //.primary=true, taken out
            &cha_on2,
            &cha_name2,
            &cha_bright2,
            &cha_sat2,
            &cha_hue2,
            NULL
      
     }),
      NULL
    }),
  NULL

};

homekit_server_config_t accessory_config = {
    .accessories = accessories,
    .password = "111-11-111"
};

**Comment by tahammert** [comment]
were you able to do this? How did you do?
