### ISSUE TITLE
Possible or not?

### ISSUE THREAD

**Issue by cyb0rk747** [Mixiaoxiao/Arduino-HomeKit-ESP8266#90]
Hello,
you´re doing a very good job!
Is there a way to get a temperature from an existing Accessory?
I guess the ESP have to be a client. Is this possible?
Thanks a lot:)

**Comment by sircuri** [comment]
Your question is rather vague. Can you please explain what you are trying to do?

**Comment by cyb0rk747** [comment]
Sure. I have 8 Weatherstations they´re posting some values to the Homekit and I have a ESP which is connected with a nextion display. I want to display all data on the display and controll switches over the display.

**Comment by Mixiaoxiao** [comment]
Possible. Write your code to do what your want.
