### ISSUE TITLE
Arduino Examples naming issue

### ISSUE THREAD

**Issue by brencerddwr** [Mixiaoxiao/Arduino-HomeKit-ESP8266#96]
The *.ino file does not match the name of the containing folder.  This causes the examples to not be recognized as arduino sketches.

The legacy examples are fine, it is the newer examples.

**Comment by DirkRussellG** [comment]
I don't that is so. Put the .c file and .h file in the same folder as sketch and try again.

**Comment by brencerddwr** [comment]
Compare the file naming structure for the legacy examples and the newer examples.  You will see a clear difference.

In Arduino IDE, if you go into file->examples->homekit-esp8266 all you will see is the legacy examples.

**Comment by brencerddwr** [comment]
I have submitted a pull request that will resolve this issue.

https://github.com/Mixiaoxiao/Arduino-HomeKit-ESP8266/pull/97

**Comment by DirkRussellG** [comment]
I assumed you were referring to the examples here on gethub

**Comment by Mixiaoxiao** [comment]
Merged.
